### ISSUE TITLE
Fix tag

### ISSUE THREAD

**Issue by mauriciovieira** [OmnicodeSolutions/react-big-calendar#6]
#### Do you want to request a _feature_ or report a _bug_?

I accidentally created a wrong tag. Please add tag `v0.28.0` and remove `fullWorkWeek` tag.

Refer to https://git-scm.com/book/en/v2/Git-Basics-Tagging

#### What's the current behavior?

```
To github.com:OmnicodeSolutions/react-big-calendar.git
 * [new tag]         fullWorkWeek -> fullWorkWeek
 * [new tag]         v0.27.1 -> v0.27.1
```

#### What's the expected behavior?

```
To github.com:OmnicodeSolutions/react-big-calendar.git
 * [new tag]         v0.28.0 -> v0.28.0
 * [new tag]         v0.27.1 -> v0.27.1
```

**Comment by mateussoaresr** [comment]
References: 

https://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag

"Please tell them (co-workers) to run the following command:"

```git pull --prune --tags```

**Comment by mateussoaresr** [comment]
@mauriciovieira, I finished the implementation, could you check it out?
