### ISSUE TITLE
Fix onResource change to return to all rooms on click again

### ISSUE THREAD

**Issue by mateussoaresr** [OmnicodeSolutions/react-big-calendar#7]
#### Do you want to request a _feature_ or report a _bug_?

The implementation of this functionality was interrupted to solve more emerging issues, however, it is necessary that the expected behavior is achieved:

#### What's the current behavior?

```
       resources.map(([id, resource], idx) => (
        <div className="rbc-time-header-content" key={id || idx}>
          {resource && (
            <div className="rbc-row rbc-row-resource" key={`resource_${idx}`}>
              <div
                resource={resource}
                className="rbc-header"
                onClick={() => props.onResourceChange([resource])}
              >
                <ResourceHeaderComponent
                  index={id}
                  label={resource.resourceTitle}
                  resource={resource}
                />
              </div>
            </div>
          )}
 ```

onResourceChange does not work to return to the initial state of the rooms.

#### What's the expected behavior?

When clicking on a room, switch the view to that room, and when clicking again return to all rooms

**Comment by mauriciovieira** [comment]
closed by #8
